# =============================================================================
# V2ParityTestDiscovery.cmake
#
# POST_BUILD helper script: runs a GTest binary with --gtest_list_tests
# (no mpirun), parses the output, and generates a CTest include file with
# one add_test() per discovered test case, each wrapped in mpirun.
#
# Inputs (via -D):
#   TEST_EXECUTABLE  - Full path to the GTest binary
#   CTEST_FILE       - Output .cmake file to generate
#   TEST_PREFIX      - CTest name prefix (e.g. V2_Integration_Parity_Qwen2_SingleDevice)
#   LABELS           - Semicolon-separated CTest labels
#   MPI_PROCS        - Number of MPI processes for test execution
#   NUM_SOCKETS      - Detected CPU socket count
#   CORES_PER_SOCKET - Cores per socket
#   WORKING_DIR      - Working directory for tests
# =============================================================================

# --- Run the binary to discover tests (no mpirun needed) --------------------
execute_process(
    COMMAND "${TEST_EXECUTABLE}" --gtest_list_tests
    OUTPUT_VARIABLE _test_list_output
    ERROR_QUIET
    RESULT_VARIABLE _result
    TIMEOUT 30
)

if(NOT _result EQUAL 0)
    message(WARNING "V2ParityTestDiscovery: Failed to list tests from ${TEST_EXECUTABLE} (exit ${_result})")
    file(WRITE "${CTEST_FILE}" "# Discovery failed for ${TEST_EXECUTABLE}\n")
    return()
endif()

# --- Parse gtest_list_tests output -------------------------------------------
# Format:
#   SuiteName.
#     TestMethod/ConfigName  # GetParam() = ...
#     TestMethod/AnotherConfig
#   AnotherSuite.
#     ...
#
# Full test name = <suite_line><case_line_trimmed>  (suite ends with '.')

set(_current_suite "")
set(_all_tests "")

string(REPLACE "\n" ";" _lines "${_test_list_output}")
foreach(_line IN LISTS _lines)
    # Skip empty lines
    if("${_line}" STREQUAL "")
        continue()
    endif()

    # Check if this is a suite line (does not start with whitespace)
    string(REGEX MATCH "^[^ ]" _is_suite "${_line}")
    if(_is_suite)
        # Suite line: strip trailing whitespace, keep the trailing dot
        string(STRIP "${_line}" _current_suite)
    else()
        # Test case line: strip leading whitespace and trailing comments
        string(STRIP "${_line}" _case_name)
        # Remove gtest parameter comment:  "  # GetParam() = ..."
        string(REGEX REPLACE "  # .*$" "" _case_name "${_case_name}")
        string(STRIP "${_case_name}" _case_name)

        if(NOT "${_case_name}" STREQUAL "" AND NOT "${_current_suite}" STREQUAL "")
            # Full GTest name: SuiteName.TestCase  (suite already has trailing dot)
            set(_full_name "${_current_suite}${_case_name}")
            list(APPEND _all_tests "${_full_name}")
        endif()
    endif()
endforeach()

list(LENGTH _all_tests _test_count)
if(_test_count EQUAL 0)
    message(WARNING "V2ParityTestDiscovery: No tests discovered from ${TEST_EXECUTABLE}")
    file(WRITE "${CTEST_FILE}" "# No tests discovered from ${TEST_EXECUTABLE}\n")
    return()
endif()

# --- Build the mpirun command prefix ----------------------------------------
if(NOT MPI_PROCS)
    set(MPI_PROCS 1)
endif()

set(_mpi_cmd
    "mpirun"
    "-np" "${MPI_PROCS}"
    "--bind-to" "socket"
    "--map-by" "socket"
    "--mca" "mpi_leave_pinned" "1"
    "--mca" "btl_vader_single_copy_mechanism" "none"
)

# Add --oversubscribe if we have fewer sockets than MPI ranks
if(NUM_SOCKETS AND MPI_PROCS GREATER NUM_SOCKETS)
    list(APPEND _mpi_cmd "--oversubscribe")
endif()

# --- Build environment variables list ----------------------------------------
if(NOT CORES_PER_SOCKET OR CORES_PER_SOCKET EQUAL "" OR CORES_PER_SOCKET EQUAL 0)
    set(CORES_PER_SOCKET 1)
endif()

set(_env_vars
    "LLAMINAR_LOG_LEVEL=DEBUG"
    "HWLOC_COMPONENTS=-gl,-opencl"
    "OMP_NUM_THREADS=${CORES_PER_SOCKET}"
    "OMP_PLACES=sockets"
    "OMP_PROC_BIND=close"
    "OMP_NESTED=false"
    "OMP_DYNAMIC=false"
    "KMP_AFFINITY=granularity=fine,compact,1,0"
    "KMP_BLOCKTIME=0"
    "MKL_NUM_THREADS=${CORES_PER_SOCKET}"
    "MKL_DYNAMIC=false"
    "OMPI_MCA_mpi_leave_pinned=1"
    "OMPI_MCA_btl_vader_single_copy_mechanism=none"
    "OMPI_MCA_btl_openib_allow_ib=1"
)

# Add ROCm env if labels mention ROCm
if("${LABELS}" MATCHES "ROCm")
    list(APPEND _env_vars "HSA_OVERRIDE_GFX_VERSION=9.0.6")
endif()

# --- Generate CTest include file --------------------------------------------
set(_output "# Auto-generated by V2ParityTestDiscovery.cmake\n")
string(APPEND _output "# Source: ${TEST_EXECUTABLE}\n")
string(APPEND _output "# Tests discovered: ${_test_count}\n\n")

foreach(_full_name IN LISTS _all_tests)
    # Sanitize the full gtest name into a valid CTest name suffix
    # Replace . / with _
    string(REPLACE "." "_" _sanitized "${_full_name}")
    string(REPLACE "/" "_" _sanitized "${_sanitized}")
    set(_ctest_name "${TEST_PREFIX}_${_sanitized}")

    # Build the full command: mpirun ... <binary> --gtest_filter=<full_name>
    set(_cmd ${_mpi_cmd} "${TEST_EXECUTABLE}" "--gtest_filter=${_full_name}")

    # Convert command list to space-separated string for add_test
    # We need to properly quote each argument
    set(_cmd_str "")
    foreach(_arg IN LISTS _cmd)
        if(_cmd_str)
            string(APPEND _cmd_str " \"${_arg}\"")
        else()
            set(_cmd_str "\"${_arg}\"")
        endif()
    endforeach()

    string(APPEND _output "add_test(\"${_ctest_name}\" ${_cmd_str})\n")

    # Escape semicolons in env vars for set_tests_properties
    string(REPLACE ";" "\\;" _env_escaped "${_env_vars}")

    string(APPEND _output "set_tests_properties(\"${_ctest_name}\" PROPERTIES\n")
    string(APPEND _output "    FIXTURES_REQUIRED \"V2_Models\"\n")
    string(APPEND _output "    LABELS \"${LABELS}\"\n")
    string(APPEND _output "    ENVIRONMENT \"${_env_escaped}\"\n")
    string(APPEND _output "    WORKING_DIRECTORY \"${WORKING_DIR}\"\n")
    string(APPEND _output "    PROCESSORS 4\n")
    # Serialize all parity tests: they load large models and consume significant
    # memory/GPU resources. Running multiple concurrently causes OOM and contention.
    string(APPEND _output "    RESOURCE_LOCK \"Parity_Model_Execution\"\n")
    string(APPEND _output ")\n\n")
endforeach()

file(WRITE "${CTEST_FILE}" "${_output}")
message(STATUS "V2ParityTestDiscovery: ${_test_count} tests from ${TEST_PREFIX}")
