/**
 * @file IntegerGemmKernelFactory.h
 * @brief Dispatch factory for Integer GEMM kernel configurations
 *
 * AUTO-GENERATED by generate_integer_gemm_dispatch_factory.py
 * DO NOT EDIT MANUALLY
 *
 * This file provides runtime dispatch to 8000 IntegerGemmKernel template
 * instantiations based on configuration parameters.
 *
 * @author David Sanftenberg
 * @date November 11, 2025
 */

#pragma once

#include <memory>
#include <string>
#include "tensors/BlockStructures.h"

namespace llaminar2
{
    namespace kernels
    {
        namespace gemm
        {

            // Q8_0BlockProvider defined in GemmWeightCache.h (included by users)
            class Q8_0BlockProvider;

            /**
             * @brief Abstract interface for kernel execution
             */
            class IntegerGemmKernelExecutor
            {
            public:
                virtual ~IntegerGemmKernelExecutor() = default;

                /**
                 * @brief Execute integer GEMM: C = A * B
                 *
                 * @param A_blocks Input activation matrix (M × K) in Q8_0 format
                 * @param B_provider Weight matrix provider (K × N) with Q8_0 blocks
                 * @param C_blocks Output matrix (M × N) in Q8_0 format
                 * @param m Number of rows in A and C
                 * @param n Number of columns in B and C
                 * @param k Number of columns in A and rows in B
                 * @return true if execution succeeded, false otherwise
                 */
                virtual bool execute(
                    const Q8_0Block *A_blocks,
                    Q8_0BlockProvider &B_provider,
                    Q8_0Block *C_blocks,
                    int m, int n, int k) = 0;
            };

            /**
             * @brief Kernel configuration parameters
             */
            struct IntegerGemmKernelConfig
            {
                std::string isa;   // ISA variant (e.g., "AVX512VNNI")
                int MR;            // Register blocking for M dimension
                int NR;            // Register blocking for N dimension (must be 32 for Q8_0)
                int UNROLL_K;      // K-dimension unroll factor
                int PREFETCH_DIST; // Prefetch distance in cache lines
                int MC;            // L1 cache blocking for M dimension
                int KC;            // L2 cache blocking for K dimension
                int NC;            // L3 cache blocking for N dimension
            };

            /**
             * @brief Create kernel executor for given configuration
             *
             * Returns nullptr if configuration not instantiated.
             *
             * @param config Kernel configuration parameters
             * @return Unique pointer to executor, or nullptr if config not available
             */
            std::unique_ptr<IntegerGemmKernelExecutor> createIntegerGemmKernelExecutor(
                const IntegerGemmKernelConfig &config);

        } // namespace gemm
    } // namespace kernels
} // namespace llaminar2
