// Auto-generated by train_cuda_heuristic.py
// DO NOT EDIT - regenerate by running performance tests

#pragma once

#include <cstddef>

namespace llaminar {
namespace cuda {

// ML-learned coefficients from Linear Regression
// Model trained to predict GFLOPS from configuration parameters
struct MLHeuristicWeights {
    static constexpr double intercept = 271.34860113;

    static constexpr double tile_m_coef = -15.00023431;
    static constexpr double tile_n_coef = -95.67042105;
    static constexpr double tile_k_coef = 0.00000000;
    static constexpr double threads_m_coef = -8.58824431;
    static constexpr double threads_n_coef = 19.21326272;
    static constexpr double work_m_coef = -30.12672112;
    static constexpr double work_n_coef = 22.59746994;
    static constexpr double prefetch_stages_coef = -0.67532609;
    static constexpr double transpose_smem_coef = -0.59272667;
    static constexpr double vectorize_load_coef = 0.00666078;
    static constexpr double m_coef = 301.49054830;
    static constexpr double n_coef = -395.08529582;
    static constexpr double k_coef = 1.97246760;
    static constexpr double threads_per_block_coef = -47.81449983;
    static constexpr double tile_size_coef = 47.04737966;
    static constexpr double tile_area_coef = 47.04737966;
    static constexpr double work_per_thread_coef = 20.06985922;
    static constexpr double occupancy_estimate_coef = 2.16501653;
    static constexpr double arithmetic_intensity_coef = -0.00000000;
    static constexpr double m_over_tile_m_coef = -307.89214210;
    static constexpr double n_over_tile_n_coef = -12.34155553;
    static constexpr double k_over_tile_k_coef = 1.97246760;
    static constexpr double tile_coverage_m_coef = 82.18981940;
    static constexpr double tile_coverage_n_coef = 0.00000000;
    static constexpr double is_tiny_coef = -236.21095942;
    static constexpr double is_small_coef = -76.01965357;
    static constexpr double is_medium_coef = 210.02035541;
    static constexpr double is_large_coef = 211.74279439;
    static constexpr double is_square_coef = 0.00000000;
    static constexpr double aspect_ratio_coef = 430.92277802;
    static constexpr double tile_aspect_ratio_coef = 40.81384777;
    static constexpr double tile_shape_match_coef = 2.20309588;

    // Scaler parameters (for feature normalization)
    struct ScalerParams {
        double mean;
        double std;
    };

    static const ScalerParams feature_scalers[32];
};

// Scaler parameters for feature normalization
inline const MLHeuristicWeights::ScalerParams MLHeuristicWeights::feature_scalers[] = {
    {37.405353, 19.945922},  // tile_m
    {37.413070, 19.959299},  // tile_n
    {32.000000, 1.000000},  // tile_k
    {11.994213, 3.999996},  // threads_m
    {12.004823, 3.999997},  // threads_n
    {3.504582, 2.284749},  // work_m
    {3.508560, 2.298627},  // work_n
    {0.997106, 0.815802},  // prefetch_stages
    {0.501326, 0.499998},  // transpose_smem
    {2.327104, 1.243627},  // vectorize_load
    {34.744635, 70.704796},  // m
    {3968.910538, 4959.335488},  // n
    {4710.211719, 6714.385809},  // k
    {144.050157, 69.867058},  // threads_per_block
    {1398.616831, 1127.004936},  // tile_size
    {44755.738606, 36064.157968},  // tile_area
    {12.280805, 12.468397},  // work_per_thread
    {0.211350, 0.150398},  // occupancy_estimate
    {0.432432, 1.000000},  // arithmetic_intensity
    {1.257645, 2.977935},  // m_over_tile_m
    {144.709187, 221.180913},  // n_over_tile_n
    {147.194116, 209.824557},  // k_over_tile_k
    {0.229443, 0.420475},  // tile_coverage_m
    {1.000000, 1.000000},  // tile_coverage_n
    {0.749940, 0.433048},  // is_tiny
    {0.062575, 0.242198},  // is_small
    {0.125030, 0.330753},  // is_medium
    {0.062455, 0.241980},  // is_large
    {0.000000, 1.000000},  // is_square
    {3183.318061, 5202.744077},  // aspect_ratio
    {1.361677, 1.101329},  // tile_aspect_ratio
    {0.333374, 0.471419},  // tile_shape_match
};

}  // namespace cuda
}  // namespace llaminar
