#!/usr/bin/env python3
"""
Generate Q8_1 GEMM kernel template instantiations with static registration.

This script generates C++ files containing explicit template instantiations
for all valid Q8_1 GEMM kernel configurations. Each configuration auto-registers
itself at program startup using __attribute__((constructor)).

Configuration Space:
- MR: 8, 16, 32, 64, 128 (micro-kernel M dimension)
- NR: 8, 16, 32, 64, 128 (micro-kernel N dimension)  
- JR_BATCH: 2, 4, 6, 8, 10, 12, 14, 16, 18 (batched reduction size)
- JR_UNROLL: 1, 2, 4, 8 (column unroll factor)
- PREFETCH_A: 1, 2, 4 (prefetch distance)

Constraints:
- JR_BATCH <= NR (can't batch more columns than exist)
- NR % JR_UNROLL == 0 (must evenly divide)
- MR % 8 == 0 and NR % 8 == 0 (vectorization alignment)

Total: ~2,000 valid configurations
Output: 64 files (~31 configs per file) for parallel compilation
"""

import os
import sys
from pathlib import Path

# Configuration space
MR_VALUES = [8, 16, 32, 64, 128]
NR_VALUES = [8, 16, 32, 64, 128]
JR_BATCH_VALUES = [2, 4, 6, 8, 10, 12, 14, 16, 18]
JR_UNROLL_VALUES = [1, 2, 4, 8]
PREFETCH_A_VALUES = [1, 2, 4]

# Output configuration
NUM_SHARDS = 64
OUTPUT_DIR = "../generated"

def is_valid_config(mr, nr, jr_batch, jr_unroll, prefetch_a):
    """Check if configuration satisfies all constraints"""
    # Vectorization alignment
    if mr % 8 != 0 or nr % 8 != 0:
        return False
    
    # JR_BATCH must be <= NR
    if jr_batch > nr:
        return False
    
    # NR must be divisible by JR_UNROLL
    if nr % jr_unroll != 0:
        return False
    
    return True

def generate_config_space():
    """Generate all valid configuration tuples"""
    configs = []
    for mr in MR_VALUES:
        for nr in NR_VALUES:
            for jr_batch in JR_BATCH_VALUES:
                for jr_unroll in JR_UNROLL_VALUES:
                    for prefetch_a in PREFETCH_A_VALUES:
                        if is_valid_config(mr, nr, jr_batch, jr_unroll, prefetch_a):
                            configs.append((mr, nr, jr_batch, jr_unroll, prefetch_a))
    return configs

def generate_file_header(shard_idx):
    """Generate file header with includes and namespace"""
    return f"""/**
 * @file Q8_1GemmInstantiations_{shard_idx:02d}.cpp
 * @brief Auto-generated Q8_1 GEMM kernel instantiations (shard {shard_idx})
 * 
 * DO NOT EDIT - Generated by generate_q8_1_gemm_instantiations.py
 */

#include "../Q8_1GemmKernel.h"
#include "../Q8_1GemmKernelRegistry.h"

using namespace llaminar2;

// Force-link symbol to prevent linker from dropping this object file
extern "C" void forceLink_Q8_1GemmInstantiations_{shard_idx:02d}() {{}}

"""

def generate_instantiation(mr, nr, jr_batch, jr_unroll, prefetch_a):
    """Generate explicit template instantiation + static registration"""
    return f"""// Configuration: MR={mr}, NR={nr}, JR_BATCH={jr_batch}, JR_UNROLL={jr_unroll}, PREFETCH_A={prefetch_a}
template class Q8_1GemmKernelTemplate<{mr}, {nr}, {prefetch_a}, 0, 0, {jr_unroll}, {jr_batch}>;

namespace {{
    __attribute__((constructor))
    void register_q8_1_gemm_{mr}_{nr}_{jr_batch}_{jr_unroll}_{prefetch_a}() {{
        Q8_1GemmKernelRegistry::instance().register_kernel(
            {mr}, {nr}, {jr_batch}, {jr_unroll}, {prefetch_a},
            [](int M, int N, int K,
               const IActivationTensor& A,
               const Q8_0Tensor& B,
               float* C, int ldc) {{
                Q8_1GemmKernelTemplate<{mr}, {nr}, {prefetch_a}, 0, 0, {jr_unroll}, {jr_batch}>::gemm(
                    M, N, K, A, B, C, ldc
                );
            }}
        );
    }}
}}

"""

def distribute_to_files(configs, num_shards):
    """Distribute configurations across shard files"""
    configs_per_shard = (len(configs) + num_shards - 1) // num_shards
    
    for shard_idx in range(num_shards):
        start_idx = shard_idx * configs_per_shard
        end_idx = min(start_idx + configs_per_shard, len(configs))
        
        if start_idx >= len(configs):
            break  # No more configs
        
        shard_configs = configs[start_idx:end_idx]
        
        # Generate file content
        content = generate_file_header(shard_idx)
        for config in shard_configs:
            mr, nr, jr_batch, jr_unroll, prefetch_a = config
            content += generate_instantiation(mr, nr, jr_batch, jr_unroll, prefetch_a)
        
        # Write to file
        output_path = Path(OUTPUT_DIR) / f"Q8_1GemmInstantiations_{shard_idx:02d}.cpp"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(content)
        
        print(f"Generated {output_path} ({len(shard_configs)} configs)")

def generate_init_file(num_shards):
    """Generate Q8_1GemmKernelInit.cpp with force-link calls"""
    content = """/**
 * @file Q8_1GemmKernelInit.cpp
 * @brief Force-link all Q8_1 GEMM kernel instantiation shards
 * 
 * DO NOT EDIT - Generated by generate_q8_1_gemm_instantiations.py
 * 
 * This file prevents the linker from dropping instantiation object files
 * from the static library. Each shard exports a forceLink symbol that
 * we call here to create a dependency.
 */

"""
    
    # Declare extern symbols
    for i in range(num_shards):
        content += f"extern \"C\" void forceLink_Q8_1GemmInstantiations_{i:02d}();\n"
    
    content += "\nnamespace llaminar2 {\n\n"
    content += "void forceLink_Q8_1GemmKernelRegistry() {\n"
    
    # Call all force-link functions
    for i in range(num_shards):
        content += f"    forceLink_Q8_1GemmInstantiations_{i:02d}();\n"
    
    content += "}\n\n} // namespace llaminar2\n"
    
    # Write to parent directory (not in generated/)
    output_path = Path("..") / "Q8_1GemmKernelInit.cpp"
    with open(output_path, 'w') as f:
        f.write(content)
    
    print(f"Generated {output_path}")

def generate_sources_cmake(num_shards):
    """Generate sources.cmake for CMake inclusion"""
    content = """# Auto-generated Q8_1 GEMM kernel instantiation sources
# DO NOT EDIT - Generated by generate_q8_1_gemm_instantiations.py

set(Q8_1_GEMM_INSTANTIATION_SOURCES
"""
    
    for i in range(num_shards):
        content += f"    kernels/cpu/gemm_v2/generated/Q8_1GemmInstantiations_{i:02d}.cpp\n"
    
    content += ")\n"
    
    # Write to generated directory
    output_path = Path(OUTPUT_DIR) / "sources.cmake"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)
    
    print(f"Generated {output_path}")

def main():
    print("Q8_1 GEMM Kernel Instantiation Generator")
    print("=" * 60)
    
    # Generate configuration space
    configs = generate_config_space()
    print(f"Total valid configurations: {len(configs)}")
    print(f"Output shards: {NUM_SHARDS}")
    print(f"Configs per shard: ~{len(configs) // NUM_SHARDS}")
    print()
    
    # Distribute to shard files
    distribute_to_files(configs, NUM_SHARDS)
    
    # Generate init file
    generate_init_file(NUM_SHARDS)
    
    # Generate sources.cmake
    generate_sources_cmake(NUM_SHARDS)
    
    print()
    print("=" * 60)
    print("Generation complete!")
    print()
    print("Next steps:")
    print("1. Rebuild: cmake --build build_v2_release --parallel")
    print("2. Verify registry size: Q8_1GemmKernelRegistry::instance().size()")


if __name__ == "__main__":
    main()
