/**
 * @file VNNIGemmKernelInit.cpp
 * @brief Force-link all VNNI GEMM kernel instantiation shards
 * 
 * DO NOT EDIT - Generated by generate_vnni_gemm_instantiations.py
 * 
 * This file prevents the linker from dropping instantiation object files
 * from the static library. Each shard exports a forceLink symbol that
 * we call here to create a dependency.
 */

extern "C" void forceLink_VNNIGemmInstantiations_00();
extern "C" void forceLink_VNNIGemmInstantiations_01();
extern "C" void forceLink_VNNIGemmInstantiations_02();
extern "C" void forceLink_VNNIGemmInstantiations_03();
extern "C" void forceLink_VNNIGemmInstantiations_04();
extern "C" void forceLink_VNNIGemmInstantiations_05();
extern "C" void forceLink_VNNIGemmInstantiations_06();
extern "C" void forceLink_VNNIGemmInstantiations_07();
extern "C" void forceLink_VNNIGemmInstantiations_08();
extern "C" void forceLink_VNNIGemmInstantiations_09();
extern "C" void forceLink_VNNIGemmInstantiations_10();
extern "C" void forceLink_VNNIGemmInstantiations_11();
extern "C" void forceLink_VNNIGemmInstantiations_12();
extern "C" void forceLink_VNNIGemmInstantiations_13();
extern "C" void forceLink_VNNIGemmInstantiations_14();
extern "C" void forceLink_VNNIGemmInstantiations_15();

namespace llaminar2 {

void forceLink_VNNIGemmKernelRegistry() {
    forceLink_VNNIGemmInstantiations_00();
    forceLink_VNNIGemmInstantiations_01();
    forceLink_VNNIGemmInstantiations_02();
    forceLink_VNNIGemmInstantiations_03();
    forceLink_VNNIGemmInstantiations_04();
    forceLink_VNNIGemmInstantiations_05();
    forceLink_VNNIGemmInstantiations_06();
    forceLink_VNNIGemmInstantiations_07();
    forceLink_VNNIGemmInstantiations_08();
    forceLink_VNNIGemmInstantiations_09();
    forceLink_VNNIGemmInstantiations_10();
    forceLink_VNNIGemmInstantiations_11();
    forceLink_VNNIGemmInstantiations_12();
    forceLink_VNNIGemmInstantiations_13();
    forceLink_VNNIGemmInstantiations_14();
    forceLink_VNNIGemmInstantiations_15();
}

} // namespace llaminar2
