"""Build a bounded, provenance-pinned inventory of production MoE GGUFs.

The ordinary and grouped-prefill trainers need to benchmark the codebook
mixtures that users actually download.  Quantization names such as
``UD-IQ3_S`` are not sufficient evidence: a mixed quant may use one format for
routed gate/up tensors, another for routed down tensors, and a third for the
shared expert, with exceptional layers using still another format.

This module reads that evidence directly from GGUF tensor descriptors hosted
on Hugging Face.  It deliberately does *not* download model payloads.  Each
HTTP request is bounded to an adaptive prefix of a pinned LFS object, metadata
arrays are skipped without materialization, and only the small tensor-info
table is retained.  Split GGUF shards are merged by tensor name before the
per-layer MoE signatures are validated and deduplicated.

The checked-in manifest generated by this module is a reviewed input to every
backend's prefill matrix.  Network access is therefore a refresh-time concern;
unit tests use synthetic in-memory GGUF headers and never contact Hugging Face.
"""

from __future__ import annotations

import argparse
import json
import re
import struct
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from .format_registry import FORMAT_BY_LABEL


MANIFEST_SCHEMA_VERSION = "qwen-moe-gguf-codebook-patterns-v1"
DEFAULT_INITIAL_PREFIX_BYTES = 16 * 1024 * 1024
DEFAULT_MAXIMUM_PREFIX_BYTES = 64 * 1024 * 1024
DEFAULT_DOWNLOAD_WORKERS = 4

# These revisions are immutable corpus provenance, not convenience defaults to
# a mutable branch.  A refresh fails if the Hub API cannot resolve exactly the
# reviewed object graph.
PINNED_QWEN_MOE_REPOSITORIES: tuple[tuple[str, str, str], ...] = (
    (
        "Qwen3.5-35B-A3B",
        "unsloth/Qwen3.5-35B-A3B-GGUF",
        "bc014a17be43adabd7066b7a86075ff935c6a4e2",
    ),
    (
        "Qwen3.5-122B-A10B",
        "unsloth/Qwen3.5-122B-A10B-GGUF",
        "51eab4d59d53f573fb9206cb3ce613f1d0aa392b",
    ),
    (
        "Qwen3.6-35B-A3B",
        "unsloth/Qwen3.6-35B-A3B-MTP-GGUF",
        "b8efbbece76dc9103a6a45b7ed95b26c3932fc5f",
    ),
)


class GGUFInventoryError(ValueError):
    """Base class for malformed or incomplete inventory evidence."""


class GGUFHeaderTruncated(GGUFInventoryError):
    """Signal that a bounded prefix ended before the tensor table did."""

    def __init__(self, required_bytes: int) -> None:
        super().__init__(
            f"GGUF header prefix is truncated; need at least {required_bytes} bytes"
        )
        self.required_bytes = required_bytes


@dataclass(frozen=True, order=True)
class HubGGUFFile:
    """One immutable GGUF object advertised by the Hugging Face model API."""

    path: str
    size_bytes: int
    sha256: str


@dataclass(frozen=True)
class HubGGUFVariant:
    """One logical quantization variant, possibly split over several shards."""

    variant_id: str
    files: tuple[HubGGUFFile, ...]


@dataclass(frozen=True)
class GGUFTensorDescriptor:
    """The payload-free part of one GGUF tensor-info record.

    ``dimensions`` remain in GGUF's fastest-dimension-first order.  For packed
    Qwen MoE tensors this is ``(K, N, experts)`` and can be validated directly
    against the release geometry without touching tensor data.
    """

    name: str
    dimensions: tuple[int, ...]
    type_id: int
    format_label: str
    payload_offset: int


@dataclass(frozen=True)
class ParsedGGUFHeader:
    """Metadata scalars and tensor descriptors from one bounded GGUF prefix."""

    version: int
    metadata: Mapping[str, object]
    tensors: tuple[GGUFTensorDescriptor, ...]
    data_offset: int


class _Cursor:
    """Bounds-checked little-endian cursor over an in-memory HTTP prefix."""

    def __init__(self, data: bytes) -> None:
        self._data = memoryview(data)
        self.offset = 0

    def take(self, size: int) -> memoryview:
        """Consume exactly ``size`` bytes or report the required prefix size."""

        if size < 0:
            raise GGUFInventoryError("GGUF field size cannot be negative")
        end = self.offset + size
        if end > len(self._data):
            raise GGUFHeaderTruncated(end)
        result = self._data[self.offset:end]
        self.offset = end
        return result

    def unpack(self, fmt: str) -> tuple[object, ...]:
        """Read one little-endian scalar tuple from the current position."""

        size = struct.calcsize(fmt)
        return struct.unpack(fmt, self.take(size))

    def unsigned32(self) -> int:
        """Read one GGUF ``uint32_t``."""

        return int(self.unpack("<I")[0])

    def unsigned64(self) -> int:
        """Read one GGUF ``uint64_t``."""

        return int(self.unpack("<Q")[0])

    def string(self, *, decode: bool = True) -> str | None:
        """Read or skip one length-prefixed GGUF UTF-8 string."""

        length = self.unsigned64()
        raw = self.take(length)
        if not decode:
            return None
        try:
            return raw.tobytes().decode("utf-8")
        except UnicodeDecodeError as error:
            raise GGUFInventoryError("GGUF string is not valid UTF-8") from error


# GGUF metadata scalar widths.  Strings and arrays are variable-sized and are
# handled separately so tokenizer arrays can be skipped without allocating a
# Python object per token.
_GGUF_VALUE_WIDTHS = {
    0: ("<B", 1),
    1: ("<b", 1),
    2: ("<H", 2),
    3: ("<h", 2),
    4: ("<I", 4),
    5: ("<i", 4),
    6: ("<f", 4),
    7: ("<B", 1),
    10: ("<Q", 8),
    11: ("<q", 8),
    12: ("<d", 8),
}
_GGUF_STRING_VALUE_TYPE = 8
_GGUF_ARRAY_VALUE_TYPE = 9
_MAXIMUM_REASONABLE_RECORD_COUNT = 10_000_000

# Only these small scalar values are useful for validating an MoE inventory.
# Everything else, especially the tokenizer, is skipped in place.
_RETAINED_METADATA_KEYS = frozenset({
    "general.architecture",
    "general.name",
    "general.basename",
    "general.file_type",
    "qwen35moe.block_count",
    "qwen35moe.expert_count",
    "qwen35moe.expert_used_count",
    "qwen35moe.expert_feed_forward_length",
    "qwen35moe.expert_shared_feed_forward_length",
    "split.no",
    "split.count",
    "split.tensors.count",
})

# Keep this table local and explicit.  Importing the third-party ``gguf``
# package in the canonical unit gate would make corpus refresh correctness
# depend on a developer-only Python environment.
_GGML_TYPE_LABELS = {
    0: "F32",
    1: "F16",
    2: "Q4_0",
    3: "Q4_1",
    6: "Q5_0",
    7: "Q5_1",
    8: "Q8_0",
    9: "Q8_1",
    10: "Q2_K",
    11: "Q3_K",
    12: "Q4_K",
    13: "Q5_K",
    14: "Q6_K",
    15: "Q8_K",
    16: "IQ2_XXS",
    17: "IQ2_XS",
    18: "IQ3_XXS",
    19: "IQ1_S",
    20: "IQ4_NL",
    21: "IQ3_S",
    22: "IQ2_S",
    23: "IQ4_XS",
    24: "I8",
    25: "I16",
    26: "I32",
    27: "I64",
    28: "F64",
    29: "IQ1_M",
    30: "BF16",
    34: "TQ1_0",
    35: "TQ2_0",
    39: "MXFP4",
}


def _metadata_value(
    cursor: _Cursor,
    value_type: int,
    *,
    retain: bool,
) -> object | None:
    """Read one GGUF metadata value while avoiding skipped-value allocation."""

    scalar = _GGUF_VALUE_WIDTHS.get(value_type)
    if scalar is not None:
        fmt, width = scalar
        raw = cursor.take(width)
        if not retain:
            return None
        value = struct.unpack(fmt, raw)[0]
        return bool(value) if value_type == 7 else value

    if value_type == _GGUF_STRING_VALUE_TYPE:
        return cursor.string(decode=retain)

    if value_type != _GGUF_ARRAY_VALUE_TYPE:
        raise GGUFInventoryError(f"unknown GGUF metadata type {value_type}")

    element_type = cursor.unsigned32()
    element_count = cursor.unsigned64()
    if element_count > _MAXIMUM_REASONABLE_RECORD_COUNT:
        raise GGUFInventoryError("GGUF metadata array count is unreasonable")
    if element_type == _GGUF_ARRAY_VALUE_TYPE:
        raise GGUFInventoryError("nested GGUF metadata arrays are unsupported")

    scalar_element = _GGUF_VALUE_WIDTHS.get(element_type)
    if scalar_element is not None:
        fmt, width = scalar_element
        raw = cursor.take(element_count * width)
        if not retain:
            return None
        return tuple(
            item[0] for item in struct.iter_unpack(fmt, raw)
        )

    if not retain:
        for _ in range(element_count):
            _metadata_value(cursor, element_type, retain=False)
        return None
    return tuple(
        _metadata_value(cursor, element_type, retain=True)
        for _ in range(element_count)
    )


def parse_gguf_header(prefix: bytes) -> ParsedGGUFHeader:
    """Parse GGUF v2/v3 metadata and tensor descriptors from a byte prefix.

    Args:
        prefix: A bounded prefix beginning at byte zero of one GGUF object.

    Returns:
        The retained metadata scalars, complete tensor-info table, and aligned
        start of payload data.

    Raises:
        GGUFHeaderTruncated: If another bounded range request is required.
        GGUFInventoryError: If the prefix is structurally invalid.
    """

    cursor = _Cursor(prefix)
    if cursor.take(4).tobytes() != b"GGUF":
        raise GGUFInventoryError("object does not begin with GGUF magic")
    version = cursor.unsigned32()
    if version not in {2, 3}:
        raise GGUFInventoryError(f"unsupported GGUF version {version}")
    tensor_count = cursor.unsigned64()
    metadata_count = cursor.unsigned64()
    if max(tensor_count, metadata_count) > _MAXIMUM_REASONABLE_RECORD_COUNT:
        raise GGUFInventoryError("GGUF record count is unreasonable")

    metadata: dict[str, object] = {}
    for _ in range(metadata_count):
        key = cursor.string()
        assert key is not None
        value_type = cursor.unsigned32()
        retain = key in _RETAINED_METADATA_KEYS
        value = _metadata_value(cursor, value_type, retain=retain)
        if retain:
            metadata[key] = value

    tensors = []
    for _ in range(tensor_count):
        name = cursor.string()
        assert name is not None
        dimension_count = cursor.unsigned32()
        if dimension_count > 8:
            raise GGUFInventoryError(
                f"{name}: unreasonable tensor rank {dimension_count}"
            )
        dimensions = tuple(cursor.unsigned64() for _ in range(dimension_count))
        if not dimensions or any(dimension <= 0 for dimension in dimensions):
            raise GGUFInventoryError(f"{name}: tensor dimensions must be positive")
        type_id = cursor.unsigned32()
        payload_offset = cursor.unsigned64()
        tensors.append(GGUFTensorDescriptor(
            name=name,
            dimensions=dimensions,
            type_id=type_id,
            format_label=_GGML_TYPE_LABELS.get(type_id, f"GGML_TYPE_{type_id}"),
            payload_offset=payload_offset,
        ))

    alignment = 32
    data_offset = (cursor.offset + alignment - 1) // alignment * alignment
    return ParsedGGUFHeader(
        version=version,
        metadata=metadata,
        tensors=tuple(tensors),
        data_offset=data_offset,
    )


_SPLIT_GGUF_RE = re.compile(
    r"^(?P<base>.+)-(?P<index>[0-9]{5})-of-(?P<count>[0-9]{5})\.gguf$"
)


def _variant_id(release_id: str, path: str) -> tuple[str, int, int]:
    """Resolve a stable quantization ID and shard coordinates from one path."""

    filename = Path(path).name
    match = _SPLIT_GGUF_RE.match(filename)
    if match is None:
        base = filename.removesuffix(".gguf")
        shard_index, shard_count = 1, 1
    else:
        base = match.group("base")
        shard_index = int(match.group("index"))
        shard_count = int(match.group("count"))
    prefix = release_id + "-"
    if not base.startswith(prefix):
        raise GGUFInventoryError(
            f"{path}: filename does not begin with release ID {release_id!r}"
        )
    return base.removeprefix(prefix), shard_index, shard_count


def group_hub_gguf_variants(
    release_id: str,
    siblings: Iterable[Mapping[str, object]],
) -> tuple[HubGGUFVariant, ...]:
    """Group API sibling records into complete logical GGUF variants."""

    grouped: dict[str, list[tuple[int, int, HubGGUFFile]]] = defaultdict(list)
    for sibling in siblings:
        path = str(sibling.get("rfilename", ""))
        lower = path.lower()
        if (
            not lower.endswith(".gguf")
            or Path(path).name.lower().startswith("mmproj")
            or "imatrix" in lower
            or "/bf16/" in f"/{lower}"
        ):
            continue
        lfs = sibling.get("lfs")
        if not isinstance(lfs, Mapping):
            raise GGUFInventoryError(f"{path}: GGUF object lacks LFS provenance")
        size = int(sibling.get("size", 0))
        sha256 = str(lfs.get("sha256", ""))
        if size <= 0 or not re.fullmatch(r"[0-9a-f]{64}", sha256):
            raise GGUFInventoryError(f"{path}: invalid LFS size or SHA256")
        variant_id, shard_index, shard_count = _variant_id(release_id, path)
        grouped[variant_id].append((
            shard_index,
            shard_count,
            HubGGUFFile(path=path, size_bytes=size, sha256=sha256),
        ))

    variants = []
    for variant_id, entries in sorted(grouped.items()):
        counts = {entry[1] for entry in entries}
        if len(counts) != 1:
            raise GGUFInventoryError(f"{variant_id}: inconsistent split count")
        shard_count = counts.pop()
        indices = [entry[0] for entry in sorted(entries)]
        if indices != list(range(1, shard_count + 1)):
            raise GGUFInventoryError(
                f"{variant_id}: incomplete shard set {indices} of {shard_count}"
            )
        variants.append(HubGGUFVariant(
            variant_id=variant_id,
            files=tuple(entry[2] for entry in sorted(entries)),
        ))
    if not variants:
        raise GGUFInventoryError(f"{release_id}: repository has no GGUF variants")
    return tuple(variants)


_MOE_TENSOR_RE = re.compile(
    r"^blk\.(?P<layer>[0-9]+)\.ffn_(?P<projection>gate|up|down)_"
    r"(?P<family>exps|shexp)\.weight$"
)
_MOE_ROLES = (
    "routed_gate",
    "routed_up",
    "routed_down",
    "shared_gate",
    "shared_up",
    "shared_down",
)


def _merged_tensor_map(headers: Sequence[ParsedGGUFHeader]) -> dict[str, GGUFTensorDescriptor]:
    """Merge split tensor tables and reject conflicting duplicate names."""

    merged: dict[str, GGUFTensorDescriptor] = {}
    for header in headers:
        for tensor in header.tensors:
            previous = merged.get(tensor.name)
            if previous is not None and (
                previous.dimensions != tensor.dimensions
                or previous.type_id != tensor.type_id
            ):
                raise GGUFInventoryError(
                    f"split GGUF disagrees about tensor {tensor.name}"
                )
            merged[tensor.name] = tensor
    return merged


def extract_moe_variant_record(
    *,
    release_id: str,
    repository: str,
    revision: str,
    variant: HubGGUFVariant,
    headers: Sequence[ParsedGGUFHeader],
) -> dict[str, object]:
    """Convert complete GGUF tensor tables into compact per-layer patterns."""

    if len(headers) != len(variant.files):
        raise GGUFInventoryError(
            f"{variant.variant_id}: expected one header per GGUF shard"
        )
    metadata_values: dict[str, set[object]] = defaultdict(set)
    for header in headers:
        for key, value in header.metadata.items():
            if key not in {"split.no", "split.count", "split.tensors.count"}:
                metadata_values[key].add(value)
    inconsistent = {
        key: values for key, values in metadata_values.items() if len(values) > 1
    }
    if inconsistent:
        raise GGUFInventoryError(
            f"{variant.variant_id}: split metadata is inconsistent: {inconsistent}"
        )
    metadata = {
        key: next(iter(values)) for key, values in metadata_values.items() if values
    }
    if metadata.get("general.architecture") != "qwen35moe":
        raise GGUFInventoryError(
            f"{variant.variant_id}: expected qwen35moe architecture"
        )
    if metadata.get("general.name") != release_id:
        raise GGUFInventoryError(
            f"{variant.variant_id}: GGUF model name does not match {release_id}"
        )

    block_count = int(metadata.get("qwen35moe.block_count", 0))
    expert_count = int(metadata.get("qwen35moe.expert_count", 0))
    expert_width = int(
        metadata.get("qwen35moe.expert_feed_forward_length", 0)
    )
    if min(block_count, expert_count, expert_width) <= 0:
        raise GGUFInventoryError(
            f"{variant.variant_id}: missing positive MoE geometry metadata"
        )

    tensors = _merged_tensor_map(headers)
    layer_roles: dict[int, dict[str, GGUFTensorDescriptor]] = defaultdict(dict)
    for tensor in tensors.values():
        match = _MOE_TENSOR_RE.match(tensor.name)
        if match is None:
            continue
        layer = int(match.group("layer"))
        family = "routed" if match.group("family") == "exps" else "shared"
        role = f"{family}_{match.group('projection')}"
        if role in layer_roles[layer]:
            raise GGUFInventoryError(
                f"{variant.variant_id}: duplicate {role} tensor in layer {layer}"
            )
        layer_roles[layer][role] = tensor

    expected_layers = set(range(block_count))
    if set(layer_roles) != expected_layers:
        missing = sorted(expected_layers - set(layer_roles))
        extra = sorted(set(layer_roles) - expected_layers)
        raise GGUFInventoryError(
            f"{variant.variant_id}: MoE layer inventory mismatch; "
            f"missing={missing}, extra={extra}"
        )
    for layer, roles in sorted(layer_roles.items()):
        if set(roles) != set(_MOE_ROLES):
            raise GGUFInventoryError(
                f"{variant.variant_id}: layer {layer} has roles {sorted(roles)}, "
                f"expected {list(_MOE_ROLES)}"
            )

    signatures: dict[tuple[str, ...], list[int]] = defaultdict(list)
    for layer, roles in sorted(layer_roles.items()):
        signatures[tuple(roles[role].format_label for role in _MOE_ROLES)].append(layer)
    layer_patterns = []
    for signature, layers in sorted(signatures.items(), key=lambda item: item[1][0]):
        layer_patterns.append({
            "layers": layers,
            "routed": {
                projection: signature[index]
                for index, projection in enumerate(("gate", "up", "down"))
            },
            "shared": {
                projection: signature[index + 3]
                for index, projection in enumerate(("gate", "up", "down"))
            },
        })

    observed_formats = sorted({
        tensor.format_label
        for roles in layer_roles.values()
        for tensor in roles.values()
    })
    unsupported_formats = sorted(set(observed_formats) - set(FORMAT_BY_LABEL))
    return {
        "release_id": release_id,
        "repository": repository,
        "revision": revision,
        "variant_id": variant.variant_id,
        "files": [
            {
                "path": file.path,
                "size_bytes": file.size_bytes,
                "sha256": file.sha256,
            }
            for file in variant.files
        ],
        "block_count": block_count,
        "expert_count": expert_count,
        "experts_per_token": int(
            metadata.get("qwen35moe.expert_used_count", 0)
        ),
        "expert_width": expert_width,
        "shared_expert_width": int(
            metadata.get("qwen35moe.expert_shared_feed_forward_length", 0)
        ),
        "observed_formats": observed_formats,
        "native_vnni_sweepable": not unsupported_formats,
        "unsupported_formats": unsupported_formats,
        "layer_patterns": layer_patterns,
    }


def _hub_api_document(repository: str, revision: str) -> Mapping[str, object]:
    """Read the pinned model API document used for LFS provenance."""

    encoded_repo = urllib.parse.quote(repository, safe="/")
    encoded_revision = urllib.parse.quote(revision, safe="")
    url = (
        f"https://huggingface.co/api/models/{encoded_repo}/revision/"
        f"{encoded_revision}?blobs=true"
    )
    try:
        with urllib.request.urlopen(url, timeout=60) as response:
            document = json.load(response)
    except (urllib.error.URLError, json.JSONDecodeError) as error:
        raise GGUFInventoryError(
            f"failed to query pinned Hugging Face repository {repository}"
        ) from error
    if not isinstance(document, Mapping) or document.get("sha") != revision:
        raise GGUFInventoryError(
            f"{repository}: Hub API did not return pinned revision {revision}"
        )
    return document


def _bounded_remote_prefix(
    repository: str,
    revision: str,
    file: HubGGUFFile,
    byte_count: int,
) -> bytes:
    """Fetch no more than ``byte_count`` leading bytes from one LFS object."""

    if byte_count <= 0 or byte_count > file.size_bytes:
        raise GGUFInventoryError("remote prefix size is outside the object")
    encoded_path = urllib.parse.quote(file.path, safe="/")
    url = (
        f"https://huggingface.co/{repository}/resolve/{revision}/"
        f"{encoded_path}?download=true"
    )
    request = urllib.request.Request(
        url,
        headers={"Range": f"bytes=0-{byte_count - 1}"},
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            # Read one sentinel byte beyond the contract.  This prevents a
            # range-ignoring origin from silently returning a multi-GB model.
            data = response.read(byte_count + 1)
    except urllib.error.URLError as error:
        raise GGUFInventoryError(f"failed to fetch header for {file.path}") from error
    if len(data) > byte_count:
        raise GGUFInventoryError(
            f"{file.path}: origin ignored bounded range response"
        )
    if len(data) != byte_count:
        raise GGUFInventoryError(
            f"{file.path}: short range response {len(data)} != {byte_count}"
        )
    return data


def fetch_parsed_header(
    repository: str,
    revision: str,
    file: HubGGUFFile,
    *,
    initial_prefix_bytes: int = DEFAULT_INITIAL_PREFIX_BYTES,
    maximum_prefix_bytes: int = DEFAULT_MAXIMUM_PREFIX_BYTES,
) -> ParsedGGUFHeader:
    """Adaptively range-fetch and parse one complete tensor-info table."""

    if initial_prefix_bytes <= 0 or maximum_prefix_bytes < initial_prefix_bytes:
        raise GGUFInventoryError("invalid adaptive GGUF prefix limits")
    prefix_size = min(initial_prefix_bytes, file.size_bytes)
    maximum = min(maximum_prefix_bytes, file.size_bytes)
    while True:
        prefix = _bounded_remote_prefix(
            repository, revision, file, prefix_size
        )
        try:
            return parse_gguf_header(prefix)
        except GGUFHeaderTruncated as error:
            if prefix_size >= maximum:
                raise GGUFInventoryError(
                    f"{file.path}: GGUF header exceeds bounded limit {maximum}"
                ) from error
            prefix_size = min(
                maximum,
                max(prefix_size * 2, error.required_bytes),
            )


def build_repository_records(
    release_id: str,
    repository: str,
    revision: str,
    *,
    variants: Sequence[str] | None = None,
    workers: int = DEFAULT_DOWNLOAD_WORKERS,
) -> tuple[dict[str, object], ...]:
    """Query, range-read, and extract every requested variant in one repo."""

    if workers <= 0:
        raise GGUFInventoryError("download worker count must be positive")
    document = _hub_api_document(repository, revision)
    siblings = document.get("siblings")
    if not isinstance(siblings, list):
        raise GGUFInventoryError(f"{repository}: Hub API lacks sibling records")
    available = group_hub_gguf_variants(release_id, siblings)
    requested = set(variants or ())
    selected = tuple(
        variant for variant in available
        if not requested or variant.variant_id in requested
    )
    missing = requested - {variant.variant_id for variant in selected}
    if missing:
        raise GGUFInventoryError(
            f"{repository}: requested variants are absent: {sorted(missing)}"
        )

    all_files = tuple(
        file for variant in selected for file in variant.files
    )
    with ThreadPoolExecutor(max_workers=min(workers, len(all_files))) as pool:
        parsed_headers = tuple(pool.map(
            lambda file: fetch_parsed_header(repository, revision, file),
            all_files,
        ))
    headers_by_path = {
        file.path: header
        for file, header in zip(all_files, parsed_headers, strict=True)
    }

    records = []
    for variant in selected:
        headers = tuple(headers_by_path[file.path] for file in variant.files)
        records.append(extract_moe_variant_record(
            release_id=release_id,
            repository=repository,
            revision=revision,
            variant=variant,
            headers=headers,
        ))
    return tuple(records)


def build_manifest(
    repositories: Sequence[tuple[str, str, str]] = PINNED_QWEN_MOE_REPOSITORIES,
    *,
    variants: Sequence[str] | None = None,
    workers: int = DEFAULT_DOWNLOAD_WORKERS,
) -> dict[str, object]:
    """Build the deterministic cross-release production codebook manifest."""

    records = []
    for release_id, repository, revision in repositories:
        records.extend(build_repository_records(
            release_id,
            repository,
            revision,
            variants=variants,
            workers=workers,
        ))
    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "sources": [
            {
                "release_id": release_id,
                "repository": repository,
                "revision": revision,
            }
            for release_id, repository, revision in repositories
        ],
        "variants": sorted(
            records,
            key=lambda record: (record["release_id"], record["variant_id"]),
        ),
    }


def main() -> int:
    """Refresh the checked-in inventory without downloading model payloads."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--variant",
        action="append",
        default=[],
        help="Refresh only this variant ID; may be repeated",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=DEFAULT_DOWNLOAD_WORKERS,
        help="Concurrent shard-header requests (bounded prefixes only)",
    )
    args = parser.parse_args()
    manifest = build_manifest(
        variants=tuple(args.variant) or None,
        workers=args.workers,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    temporary.write_text(
        json.dumps(manifest, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
