"""Deterministic MoE expert-load profiles shared by corpus transactions.

The profile-name inventory is read from the same ``.def`` file included by the
CUDA and ROCm C++ trainers. The integer route generator mirrors the trainer
algorithm so authentication can prove that reported load statistics belong to
the declared profile, M, top-k, and expert count rather than accepting a label
at face value.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from pathlib import Path


_PROFILE_DEFINITION = Path(__file__).with_name(
    "NativeVNNIMoERoutingProfiles.def"
)
_PROFILE_PATTERN = re.compile(
    r"^LLAMINAR_MOE_ROUTING_PROFILE\([A-Za-z][A-Za-z0-9_]*,\s*"
    r"(?P<name>[a-z][a-z0-9_]*)\)$"
)
_UINT64_MASK = (1 << 64) - 1


def _load_profile_names() -> tuple[str, ...]:
    """Read the ordered C++/Python profile ABI from its macro definition."""

    names = []
    for line_number, raw_line in enumerate(
        _PROFILE_DEFINITION.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("/**") or line.startswith("*") or (
            line.startswith("*/")
        ):
            continue
        match = _PROFILE_PATTERN.fullmatch(line)
        if match is None:
            raise ValueError(
                f"{_PROFILE_DEFINITION}:{line_number}: invalid profile row"
            )
        names.append(match["name"])
    if not names or len(names) != len(set(names)):
        raise ValueError("MoE routing profile inventory is empty or duplicated")
    return tuple(names)


MOE_ROUTING_PROFILES = _load_profile_names()


@dataclass(frozen=True)
class MoERoutingProfileStats:
    """Authenticated expert-assignment pressure for one route matrix."""

    active_experts: int
    maximum_assignments: int
    assignment_cv: float


def _mix_route_ordinal(value: int) -> int:
    """Mirror the trainer's wrapping SplitMix64 integer permutation."""

    value = (value + 0x9E3779B97F4A7C15) & _UINT64_MASK
    value = ((value ^ (value >> 30)) * 0xBF58476D1CE4E5B9) & _UINT64_MASK
    value = ((value ^ (value >> 27)) * 0x94D049BB133111EB) & _UINT64_MASK
    return (value ^ (value >> 31)) & _UINT64_MASK


def make_moe_routing_indices(
    profile: str,
    rows: int,
    top_k: int,
    num_experts: int,
) -> tuple[int, ...]:
    """Build the exact integer route matrix generated by the C++ trainers."""

    if profile not in MOE_ROUTING_PROFILES:
        raise ValueError(f"unknown MoE routing profile {profile!r}")
    if rows <= 0 or top_k <= 0 or num_experts <= 0 or top_k > num_experts:
        raise ValueError("routes require rows>0 and 0<top_k<=num_experts")

    routes: list[int] = []
    hot_experts = max(top_k, min(num_experts, (num_experts + 7) // 8))
    for row in range(rows):
        row_routes: list[int] = []
        for slot in range(top_k):
            if profile == "uniform":
                expert = (row * top_k + slot) % num_experts
            elif profile == "hotset":
                expert = (row * (top_k + 1) + slot) % hot_experts
            else:
                ordinal = row * top_k + slot
                uniform = _mix_route_ordinal(ordinal) >> 32
                biased = (uniform * uniform) >> 32
                expert = (biased * num_experts) >> 32
                while expert in row_routes:
                    expert = (expert + 1) % num_experts
            row_routes.append(expert)
        routes.extend(row_routes)
    return tuple(routes)


def summarize_moe_routing_profile(
    profile: str,
    rows: int,
    top_k: int,
    num_experts: int,
) -> MoERoutingProfileStats:
    """Return expected active count, maximum load, and all-expert load CV."""

    routes = make_moe_routing_indices(profile, rows, top_k, num_experts)
    counts = [0] * num_experts
    for expert in routes:
        counts[expert] += 1
    mean = len(routes) / num_experts
    variance = sum((count - mean) ** 2 for count in counts) / num_experts
    return MoERoutingProfileStats(
        active_experts=sum(count != 0 for count in counts),
        maximum_assignments=max(counts),
        assignment_cv=math.sqrt(variance) / mean,
    )
