/**
 * @file NativeVNNIMoERoutingProfiles.h
 * @brief Deterministic expert-load profiles for production MoE tuning evidence.
 *
 * MoE launch economy depends on the distribution of routed rows, not merely on
 * the total token count. A round-robin fixture gives every expert nearly equal
 * work and can therefore select a launch geometry that regresses on a real
 * prompt with concentrated routing. This header gives the CUDA and ROCm
 * trainers one shared set of deterministic route profiles. Every profile keeps
 * expert IDs unique within a token, as required by the production router, while
 * deliberately changing the load distribution across tokens.
 *
 * These helpers are trainer-only. Production inference consumes the router's
 * device-resident output and never synthesizes or inspects these host routes.
 */

#pragma once

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace llaminar2::test::native_vnni_dispatch
{
    /**
     * @brief Stable expert-load regimes represented in every MoE timing corpus.
     */
    enum class MoERoutingProfile
    {
#define LLAMINAR_MOE_ROUTING_PROFILE(enum_name, corpus_name) enum_name,
#include "NativeVNNIMoERoutingProfiles.def"
#undef LLAMINAR_MOE_ROUTING_PROFILE
    };

    /** Complete profile inventory used by corpus planning and C++ execution. */
    inline constexpr auto kMoERoutingProfiles = std::array{
#define LLAMINAR_MOE_ROUTING_PROFILE(enum_name, corpus_name) \
        MoERoutingProfile::enum_name,
#include "NativeVNNIMoERoutingProfiles.def"
#undef LLAMINAR_MOE_ROUTING_PROFILE
    };

    /**
     * @brief Summary of the expert-assignment pressure generated by one profile.
     */
    struct MoERoutingProfileStats
    {
        int active_experts = 0;
        int maximum_assignments = 0;
        double assignment_cv = 0.0;
    };

    /**
     * @brief Return the stable corpus spelling for a routing profile.
     *
     * @param profile Typed routing profile.
     * @return Stable lowercase identifier written into corpus identity and CSV.
     */
    inline constexpr std::string_view moeRoutingProfileName(
        MoERoutingProfile profile)
    {
        switch (profile)
        {
#define LLAMINAR_MOE_ROUTING_PROFILE(enum_name, corpus_name) \
            case MoERoutingProfile::enum_name:                       \
                return #corpus_name;
#include "NativeVNNIMoERoutingProfiles.def"
#undef LLAMINAR_MOE_ROUTING_PROFILE
        }
        throw std::invalid_argument("unknown MoE routing profile enum");
    }

    /**
     * @brief Parse one exact corpus profile name.
     *
     * Unknown names are fatal because silently substituting uniform routing
     * would authenticate timing evidence for a workload that did not run.
     *
     * @param value Stable lowercase profile name.
     * @return Parsed typed profile.
     */
    inline MoERoutingProfile parseMoERoutingProfile(std::string_view value)
    {
        for (const MoERoutingProfile profile : kMoERoutingProfiles)
        {
            if (value == moeRoutingProfileName(profile))
                return profile;
        }
        throw std::invalid_argument(
            "unknown MoE routing profile '" + std::string(value) + "'");
    }

    namespace detail
    {
        /**
         * @brief Stable integer mixer used to distribute power-law quantiles.
         *
         * SplitMix64 is used only as a deterministic permutation. There is no
         * stochastic state and therefore no seed or backend-dependent behavior.
         */
        inline constexpr uint64_t mixRouteOrdinal(uint64_t value) noexcept
        {
            value += UINT64_C(0x9e3779b97f4a7c15);
            value = (value ^ (value >> 30)) * UINT64_C(0xbf58476d1ce4e5b9);
            value = (value ^ (value >> 27)) * UINT64_C(0x94d049bb133111eb);
            return value ^ (value >> 31);
        }

        /** @brief Return whether an expert already appears in the current row. */
        inline bool routeRowContains(
            const std::vector<float> &routes,
            int row,
            int populated_slots,
            int top_k,
            int expert)
        {
            const size_t row_offset = static_cast<size_t>(row) * top_k;
            for (int slot = 0; slot < populated_slots; ++slot)
            {
                if (static_cast<int>(routes[row_offset + slot]) == expert)
                    return true;
            }
            return false;
        }
    } // namespace detail

    /**
     * @brief Build one deterministic row-major production routing matrix.
     *
     * `Uniform` reproduces the historical round-robin fixture. `Hotset` confines
     * traffic to max(top_k, ceil(experts/8)) experts, modelling a concentrated
     * prompt. `PowerLaw` maps a deterministic uniform permutation through u^2,
     * producing an intermediate hot-head/long-tail regime. Linear probing only
     * resolves duplicate IDs within one row and never changes profile identity.
     *
     * @param profile Desired load distribution.
     * @param rows Number of token rows.
     * @param top_k Unique expert routes per token.
     * @param num_experts Number of routed experts in the descriptor table.
     * @return FP32 expert IDs matching the production router tensor contract.
     */
    inline std::vector<float> makeMoERoutingIndices(
        MoERoutingProfile profile,
        int rows,
        int top_k,
        int num_experts)
    {
        if (rows <= 0 || top_k <= 0 || num_experts <= 0 || top_k > num_experts)
        {
            throw std::invalid_argument(
                "MoE route profile requires rows>0 and 0<top_k<=num_experts");
        }

        std::vector<float> routes(static_cast<size_t>(rows) * top_k);
        const int hot_experts = std::max(
            top_k,
            std::min(num_experts, (num_experts + 7) / 8));
        for (int row = 0; row < rows; ++row)
        {
            for (int slot = 0; slot < top_k; ++slot)
            {
                int expert = 0;
                switch (profile)
                {
                    case MoERoutingProfile::Uniform:
                        expert = (row * top_k + slot) % num_experts;
                        break;

                    case MoERoutingProfile::Hotset:
                        expert = (row * (top_k + 1) + slot) % hot_experts;
                        break;

                    case MoERoutingProfile::PowerLaw:
                    {
                        const uint64_t ordinal =
                            static_cast<uint64_t>(row) * top_k + slot;
                        const uint32_t uniform = static_cast<uint32_t>(
                            detail::mixRouteOrdinal(ordinal) >> 32);
                        const uint32_t biased = static_cast<uint32_t>(
                            (static_cast<uint64_t>(uniform) * uniform) >> 32);
                        expert = static_cast<int>(
                            (static_cast<uint64_t>(biased) * num_experts) >> 32);
                        while (detail::routeRowContains(
                            routes, row, slot, top_k, expert))
                        {
                            expert = (expert + 1) % num_experts;
                        }
                        break;
                    }
                }
                routes[static_cast<size_t>(row) * top_k + slot] =
                    static_cast<float>(expert);
            }
        }
        return routes;
    }

    /**
     * @brief Summarize one generated route matrix for corpus diagnostics.
     *
     * The coefficient of variation includes inactive experts. This makes zero
     * for a perfectly balanced full assignment and rises as work concentrates,
     * which is the pressure relevant to grouped launch geometry.
     *
     * @param routes Row-major FP32 expert IDs.
     * @param num_experts Number of routed experts.
     * @return Active count, maximum load, and all-expert load CV.
     */
    inline MoERoutingProfileStats summarizeMoERoutingProfile(
        const std::vector<float> &routes,
        int num_experts)
    {
        if (routes.empty() || num_experts <= 0)
        {
            throw std::invalid_argument(
                "MoE route summary requires routes and positive expert count");
        }
        std::vector<uint64_t> counts(static_cast<size_t>(num_experts), 0);
        for (const float encoded_expert : routes)
        {
            const int expert = static_cast<int>(encoded_expert);
            if (expert < 0 || expert >= num_experts ||
                encoded_expert != static_cast<float>(expert))
            {
                throw std::invalid_argument(
                    "MoE route summary received an invalid expert ID");
            }
            ++counts[static_cast<size_t>(expert)];
        }

        MoERoutingProfileStats result{};
        uint64_t maximum = 0;
        for (const uint64_t count : counts)
        {
            result.active_experts += count != 0 ? 1 : 0;
            maximum = std::max(maximum, count);
        }
        result.maximum_assignments = static_cast<int>(maximum);

        const double mean = static_cast<double>(routes.size()) / num_experts;
        double squared_deviation_sum = 0.0;
        for (const uint64_t count : counts)
        {
            const double deviation = static_cast<double>(count) - mean;
            squared_deviation_sum += deviation * deviation;
        }
        result.assignment_cv =
            std::sqrt(squared_deviation_sum / num_experts) / mean;
        return result;
    }
} // namespace llaminar2::test::native_vnni_dispatch
