/**
 * @file CUDANativeVNNIGemvShard7.cu
 * @brief CUDA NativeVNNI GEMV instantiations for IQ1_M and normalized INT8.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 7
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_7
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(17); MACRO(19); MACRO(23)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
