/**
 * @file CUDANativeVNNIGemvShard4.cu
 * @brief CUDA NativeVNNI GEMV instantiations for IQ3_S and IQ3_XXS.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 4
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_4
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(11); MACRO(12)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
