/**
 * @file CUDANativeVNNIGemvShard2.cu
 * @brief CUDA NativeVNNI GEMV instantiations for Q5_1 and Q8_0.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 2
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_2
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(7); MACRO(8)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
