/**
 * @file CUDANativeVNNIGemvShard3.cu
 * @brief CUDA NativeVNNI GEMV instantiations for Q6_K and Q2_K.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 3
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_3
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(9); MACRO(10)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
