/**
 * @file CUDANativeVNNIGemvShard6.cu
 * @brief CUDA NativeVNNI GEMV instantiations for IQ2_XXS and IQ1_S.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 6
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_6
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(15); MACRO(16)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
