/**
 * @file CUDANativeVNNIGemvShard5.cu
 * @brief CUDA NativeVNNI GEMV instantiations for IQ2_S and IQ2_XS.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 5
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_5
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(13); MACRO(14)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
