/**
 * @file CUDANativeVNNIGemvShard0.cu
 * @brief CUDA NativeVNNI GEMV instantiations for Q4_0 and IQ4_NL.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 0
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_0
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(0); MACRO(4)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
