/**
 * @file CUDANativeVNNIGemvShard1.cu
 * @brief CUDA NativeVNNI GEMV instantiations for Q4_1 and Q5_0.
 */
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD 1
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME) NAME##_shard_1
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL(NAME) \
    LLAMINAR_CUDA_NATIVE_VNNI_GEMV_SHARD_SYMBOL_IMPL(NAME)
#define LLAMINAR_CUDA_NATIVE_VNNI_GEMV_FOR_EACH_CODEBOOK(MACRO) \
    MACRO(5); MACRO(6)
#include "CUDANativeVNNIGemvShardImpl.cu.inc"
