#!/usr/bin/env python3
"""
Generate VNNI GEMM kernel template instantiations with static registration.

This script generates C++ files containing explicit template instantiations
for all valid VNNI GEMM kernel configurations. Each configuration auto-registers
itself at program startup using __attribute__((constructor)).

Configuration Space:
- M_R: 8, 16, 32, 64 (micro-kernel M dimension)
- N_R: 16, 32, 64 (micro-kernel N dimension)  
- K_BLK: 32, 64, 128 (K block size for VNNI layout)
- UNROLL_K: 1, 2, 4 (K-loop unroll factor)
- PREFETCH_B_L1: 0, 64, 128, 256 (L1 prefetch distance)

Constraints:
- M_R % 8 == 0 and N_R % 8 == 0 (vectorization alignment)
- K_BLK must be multiple of 4 (VNNI requirement)
- N_R >= 16 (minimum for VNNI efficiency)

Total: ~576 valid configurations
Output: 16 files (~36 configs per file) for parallel compilation
"""

import os
import sys
from pathlib import Path

# Configuration space
M_R_VALUES = [8, 16, 32, 64]
N_R_VALUES = [16, 32, 64]
K_BLK_VALUES = [32, 64, 128]
UNROLL_K_VALUES = [1, 2, 4]
PREFETCH_B_L1_VALUES = [0, 64, 128, 256]

# Fixed template parameters
PREFETCH_B_L2 = 256
ACCUM_INT32 = "true"
USE_L2_PREFETCH = "true"
USE_VNNI = "true"

# Output configuration
NUM_SHARDS = 16
OUTPUT_DIR = "../generated"

def is_valid_config(m_r, n_r, k_blk, unroll_k, prefetch_b_l1):
    """Check if configuration satisfies all constraints"""
    # Vectorization alignment
    if m_r % 8 != 0 or n_r % 8 != 0:
        return False
    
    # K_BLK must be multiple of 4 for VNNI
    if k_blk % 4 != 0:
        return False
    
    # N_R must be >= 16 for VNNI efficiency
    if n_r < 16:
        return False
    
    return True

def generate_config_space():
    """Generate all valid configuration tuples"""
    configs = []
    for m_r in M_R_VALUES:
        for n_r in N_R_VALUES:
            for k_blk in K_BLK_VALUES:
                for unroll_k in UNROLL_K_VALUES:
                    for prefetch_b_l1 in PREFETCH_B_L1_VALUES:
                        if is_valid_config(m_r, n_r, k_blk, unroll_k, prefetch_b_l1):
                            configs.append((m_r, n_r, k_blk, unroll_k, prefetch_b_l1))
    return configs

def generate_file_header(shard_idx):
    """Generate file header with includes and namespace"""
    return f"""/**
 * @file VNNIGemmInstantiations_{shard_idx:02d}.cpp
 * @brief Auto-generated VNNI GEMM kernel instantiations (shard {shard_idx})
 * 
 * DO NOT EDIT - Generated by generate_vnni_gemm_instantiations.py
 */

#include "../VNNIGemm.h"
#include "../VNNIGemmKernelRegistry.h"
#include "../VNNIGemmAdapter.h"

using namespace llaminar2;

// Force-link symbol to prevent linker from dropping this object file
extern "C" void forceLink_VNNIGemmInstantiations_{shard_idx:02d}() {{}}

"""

def generate_instantiation(m_r, n_r, k_blk, unroll_k, prefetch_b_l1):
    """Generate explicit template instantiation + static registration"""
    return f"""// Configuration: M_R={m_r}, N_R={n_r}, K_BLK={k_blk}, UNROLL_K={unroll_k}, PREFETCH_B_L1={prefetch_b_l1}
template void gemm_int8_vnni_kernel<
    {m_r}, {n_r}, {k_blk}, {unroll_k},
    {prefetch_b_l1}, {PREFETCH_B_L2},
    {ACCUM_INT32}, {USE_L2_PREFETCH}, {USE_VNNI}  // ACCUM_INT32, USE_L2_PREFETCH, USE_VNNI
>(
    const int8_t* __restrict A,
    const PackedB& Bp,
    float* __restrict C,
    const float* __restrict bias,
    const float* __restrict act_scales,
    const float* __restrict wgt_scales,
    int M, int N, int K
);

namespace {{
    __attribute__((constructor))
    void register_vnni_gemm_{m_r}_{n_r}_{k_blk}_{unroll_k}_{prefetch_b_l1}() {{
        VNNIGemmKernelRegistry::instance().register_kernel(
            {m_r}, {n_r}, {k_blk}, {unroll_k}, {prefetch_b_l1},
            [](int M, int N, int K,
               const IActivationTensor& A,
               const Q8_0Tensor& B,
               float* C, int ldc) {{
                vnni_gemm_adapter<{m_r}, {n_r}, {k_blk}, {unroll_k}, {prefetch_b_l1}>(M, N, K, A, B, C, ldc);
            }}
        );
    }}
}}

"""

def distribute_to_files(configs, num_shards):
    """Distribute configurations across shard files"""
    configs_per_shard = (len(configs) + num_shards - 1) // num_shards
    
    for shard_idx in range(num_shards):
        start_idx = shard_idx * configs_per_shard
        end_idx = min(start_idx + configs_per_shard, len(configs))
        
        if start_idx >= len(configs):
            break  # No more configs
        
        shard_configs = configs[start_idx:end_idx]
        
        # Generate file content
        content = generate_file_header(shard_idx)
        for config in shard_configs:
            m_r, n_r, k_blk, unroll_k, prefetch_b_l1 = config
            content += generate_instantiation(m_r, n_r, k_blk, unroll_k, prefetch_b_l1)
        
        # Write to file
        output_path = Path(OUTPUT_DIR) / f"VNNIGemmInstantiations_{shard_idx:02d}.cpp"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(content)
        
        print(f"Generated {output_path} ({len(shard_configs)} configs)")

def generate_init_file(num_shards):
    """Generate VNNIGemmKernelInit.cpp with force-link calls"""
    content = """/**
 * @file VNNIGemmKernelInit.cpp
 * @brief Force-link all VNNI GEMM kernel instantiation shards
 * 
 * DO NOT EDIT - Generated by generate_vnni_gemm_instantiations.py
 * 
 * This file prevents the linker from dropping instantiation object files
 * from the static library. Each shard exports a forceLink symbol that
 * we call here to create a dependency.
 */

"""
    
    # Declare extern symbols
    for i in range(num_shards):
        content += f"extern \"C\" void forceLink_VNNIGemmInstantiations_{i:02d}();\n"
    
    content += "\nnamespace llaminar2 {\n\n"
    content += "void forceLink_VNNIGemmKernelRegistry() {\n"
    
    # Call all force-link functions
    for i in range(num_shards):
        content += f"    forceLink_VNNIGemmInstantiations_{i:02d}();\n"
    
    content += "}\n\n} // namespace llaminar2\n"
    
    # Write to parent directory (not in generated/)
    output_path = Path("..") / "VNNIGemmKernelInit.cpp"
    with open(output_path, 'w') as f:
        f.write(content)
    
    print(f"Generated {output_path}")

def generate_sources_cmake(num_shards):
    """Generate sources.cmake for CMake inclusion"""
    content = """# Auto-generated VNNI GEMM kernel instantiation sources
# DO NOT EDIT - Generated by generate_vnni_gemm_instantiations.py

set(VNNI_GEMM_INSTANTIATION_SOURCES
"""
    
    for i in range(num_shards):
        content += f"    kernels/cpu/gemm_v3/generated/VNNIGemmInstantiations_{i:02d}.cpp\n"
    
    content += ")\n"
    
    # Write to generated directory
    output_path = Path(OUTPUT_DIR) / "sources.cmake"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)
    
    print(f"Generated {output_path}")

def main():
    print("VNNI GEMM Kernel Instantiation Generator")
    print("=" * 60)
    
    # Generate configuration space
    configs = generate_config_space()
    print(f"Total valid configurations: {len(configs)}")
    print(f"Output shards: {NUM_SHARDS}")
    print(f"Configs per shard: ~{len(configs) // NUM_SHARDS}")
    print()
    
    # Distribute to shard files
    distribute_to_files(configs, NUM_SHARDS)
    
    # Generate init file
    generate_init_file(NUM_SHARDS)
    
    # Generate sources.cmake
    generate_sources_cmake(NUM_SHARDS)
    
    print()
    print("=" * 60)
    print("Generation complete!")
    print()
    print("Next steps:")
    print("1. Add to src/v2/CMakeLists.txt:")
    print("   include(kernels/cpu/gemm_v3/generated/sources.cmake)")
    print("   target_sources(llaminar2_core PRIVATE ${VNNI_GEMM_INSTANTIATION_SOURCES})")
    print("2. Rebuild: cmake --build build_v2_release --parallel")
    print("3. Verify registry size: VNNIGemmKernelRegistry::instance().size()")


if __name__ == "__main__":
    main()
