/**
 * @file Q8_1GemmKernelInit.cpp
 * @brief Force-link all Q8_1 GEMM kernel instantiation shards
 * 
 * DO NOT EDIT - Generated by generate_q8_1_gemm_instantiations.py
 * 
 * This file prevents the linker from dropping instantiation object files
 * from the static library. Each shard exports a forceLink symbol that
 * we call here to create a dependency.
 */

extern "C" void forceLink_Q8_1GemmInstantiations_00();
extern "C" void forceLink_Q8_1GemmInstantiations_01();
extern "C" void forceLink_Q8_1GemmInstantiations_02();
extern "C" void forceLink_Q8_1GemmInstantiations_03();
extern "C" void forceLink_Q8_1GemmInstantiations_04();
extern "C" void forceLink_Q8_1GemmInstantiations_05();
extern "C" void forceLink_Q8_1GemmInstantiations_06();
extern "C" void forceLink_Q8_1GemmInstantiations_07();
extern "C" void forceLink_Q8_1GemmInstantiations_08();
extern "C" void forceLink_Q8_1GemmInstantiations_09();
extern "C" void forceLink_Q8_1GemmInstantiations_10();
extern "C" void forceLink_Q8_1GemmInstantiations_11();
extern "C" void forceLink_Q8_1GemmInstantiations_12();
extern "C" void forceLink_Q8_1GemmInstantiations_13();
extern "C" void forceLink_Q8_1GemmInstantiations_14();
extern "C" void forceLink_Q8_1GemmInstantiations_15();
extern "C" void forceLink_Q8_1GemmInstantiations_16();
extern "C" void forceLink_Q8_1GemmInstantiations_17();
extern "C" void forceLink_Q8_1GemmInstantiations_18();
extern "C" void forceLink_Q8_1GemmInstantiations_19();
extern "C" void forceLink_Q8_1GemmInstantiations_20();
extern "C" void forceLink_Q8_1GemmInstantiations_21();
extern "C" void forceLink_Q8_1GemmInstantiations_22();
extern "C" void forceLink_Q8_1GemmInstantiations_23();
extern "C" void forceLink_Q8_1GemmInstantiations_24();
extern "C" void forceLink_Q8_1GemmInstantiations_25();
extern "C" void forceLink_Q8_1GemmInstantiations_26();
extern "C" void forceLink_Q8_1GemmInstantiations_27();
extern "C" void forceLink_Q8_1GemmInstantiations_28();
extern "C" void forceLink_Q8_1GemmInstantiations_29();
extern "C" void forceLink_Q8_1GemmInstantiations_30();
extern "C" void forceLink_Q8_1GemmInstantiations_31();
extern "C" void forceLink_Q8_1GemmInstantiations_32();
extern "C" void forceLink_Q8_1GemmInstantiations_33();
extern "C" void forceLink_Q8_1GemmInstantiations_34();
extern "C" void forceLink_Q8_1GemmInstantiations_35();
extern "C" void forceLink_Q8_1GemmInstantiations_36();
extern "C" void forceLink_Q8_1GemmInstantiations_37();
extern "C" void forceLink_Q8_1GemmInstantiations_38();
extern "C" void forceLink_Q8_1GemmInstantiations_39();
extern "C" void forceLink_Q8_1GemmInstantiations_40();
extern "C" void forceLink_Q8_1GemmInstantiations_41();
extern "C" void forceLink_Q8_1GemmInstantiations_42();
extern "C" void forceLink_Q8_1GemmInstantiations_43();
extern "C" void forceLink_Q8_1GemmInstantiations_44();
extern "C" void forceLink_Q8_1GemmInstantiations_45();
extern "C" void forceLink_Q8_1GemmInstantiations_46();
extern "C" void forceLink_Q8_1GemmInstantiations_47();
extern "C" void forceLink_Q8_1GemmInstantiations_48();
extern "C" void forceLink_Q8_1GemmInstantiations_49();
extern "C" void forceLink_Q8_1GemmInstantiations_50();
extern "C" void forceLink_Q8_1GemmInstantiations_51();
extern "C" void forceLink_Q8_1GemmInstantiations_52();
extern "C" void forceLink_Q8_1GemmInstantiations_53();
extern "C" void forceLink_Q8_1GemmInstantiations_54();
extern "C" void forceLink_Q8_1GemmInstantiations_55();
extern "C" void forceLink_Q8_1GemmInstantiations_56();
extern "C" void forceLink_Q8_1GemmInstantiations_57();
extern "C" void forceLink_Q8_1GemmInstantiations_58();
extern "C" void forceLink_Q8_1GemmInstantiations_59();
extern "C" void forceLink_Q8_1GemmInstantiations_60();
extern "C" void forceLink_Q8_1GemmInstantiations_61();
extern "C" void forceLink_Q8_1GemmInstantiations_62();
extern "C" void forceLink_Q8_1GemmInstantiations_63();

namespace llaminar2 {

void forceLink_Q8_1GemmKernelRegistry() {
    forceLink_Q8_1GemmInstantiations_00();
    forceLink_Q8_1GemmInstantiations_01();
    forceLink_Q8_1GemmInstantiations_02();
    forceLink_Q8_1GemmInstantiations_03();
    forceLink_Q8_1GemmInstantiations_04();
    forceLink_Q8_1GemmInstantiations_05();
    forceLink_Q8_1GemmInstantiations_06();
    forceLink_Q8_1GemmInstantiations_07();
    forceLink_Q8_1GemmInstantiations_08();
    forceLink_Q8_1GemmInstantiations_09();
    forceLink_Q8_1GemmInstantiations_10();
    forceLink_Q8_1GemmInstantiations_11();
    forceLink_Q8_1GemmInstantiations_12();
    forceLink_Q8_1GemmInstantiations_13();
    forceLink_Q8_1GemmInstantiations_14();
    forceLink_Q8_1GemmInstantiations_15();
    forceLink_Q8_1GemmInstantiations_16();
    forceLink_Q8_1GemmInstantiations_17();
    forceLink_Q8_1GemmInstantiations_18();
    forceLink_Q8_1GemmInstantiations_19();
    forceLink_Q8_1GemmInstantiations_20();
    forceLink_Q8_1GemmInstantiations_21();
    forceLink_Q8_1GemmInstantiations_22();
    forceLink_Q8_1GemmInstantiations_23();
    forceLink_Q8_1GemmInstantiations_24();
    forceLink_Q8_1GemmInstantiations_25();
    forceLink_Q8_1GemmInstantiations_26();
    forceLink_Q8_1GemmInstantiations_27();
    forceLink_Q8_1GemmInstantiations_28();
    forceLink_Q8_1GemmInstantiations_29();
    forceLink_Q8_1GemmInstantiations_30();
    forceLink_Q8_1GemmInstantiations_31();
    forceLink_Q8_1GemmInstantiations_32();
    forceLink_Q8_1GemmInstantiations_33();
    forceLink_Q8_1GemmInstantiations_34();
    forceLink_Q8_1GemmInstantiations_35();
    forceLink_Q8_1GemmInstantiations_36();
    forceLink_Q8_1GemmInstantiations_37();
    forceLink_Q8_1GemmInstantiations_38();
    forceLink_Q8_1GemmInstantiations_39();
    forceLink_Q8_1GemmInstantiations_40();
    forceLink_Q8_1GemmInstantiations_41();
    forceLink_Q8_1GemmInstantiations_42();
    forceLink_Q8_1GemmInstantiations_43();
    forceLink_Q8_1GemmInstantiations_44();
    forceLink_Q8_1GemmInstantiations_45();
    forceLink_Q8_1GemmInstantiations_46();
    forceLink_Q8_1GemmInstantiations_47();
    forceLink_Q8_1GemmInstantiations_48();
    forceLink_Q8_1GemmInstantiations_49();
    forceLink_Q8_1GemmInstantiations_50();
    forceLink_Q8_1GemmInstantiations_51();
    forceLink_Q8_1GemmInstantiations_52();
    forceLink_Q8_1GemmInstantiations_53();
    forceLink_Q8_1GemmInstantiations_54();
    forceLink_Q8_1GemmInstantiations_55();
    forceLink_Q8_1GemmInstantiations_56();
    forceLink_Q8_1GemmInstantiations_57();
    forceLink_Q8_1GemmInstantiations_58();
    forceLink_Q8_1GemmInstantiations_59();
    forceLink_Q8_1GemmInstantiations_60();
    forceLink_Q8_1GemmInstantiations_61();
    forceLink_Q8_1GemmInstantiations_62();
    forceLink_Q8_1GemmInstantiations_63();
}

} // namespace llaminar2
