/**
 * @file Q8_1GemmKernelRegistry.h
 * @brief Runtime registry for Q8_1 GEMM kernel template instantiations
 * @author David Sanftenberg
 *
 * This registry enables runtime dispatch to compile-time specialized Q8_1 GEMM kernels
 * without virtual function overhead. Follows the same pattern as GEMM v1 IntegerGemmKernelRegistry.
 *
 * Design:
 * - Template instantiations are generated by Python script (generate_q8_1_gemm_instantiations.py)
 * - Each instantiation auto-registers itself using __attribute__((constructor))
 * - Registry provides O(log n) lookup by (MR, NR, JR_BATCH, JR_UNROLL, PREFETCH_A) key
 * - Force-link mechanism prevents linker from dropping unused instantiations
 *
 * Configuration Space:
 * - MR: 8, 16, 32, 64, 128 (micro-kernel M dimension)
 * - NR: 8, 16, 32, 64, 128 (micro-kernel N dimension)
 * - JR_BATCH: 2, 4, 6, 8, 10, 12, 14, 16, 18 (batched reduction size)
 * - JR_UNROLL: 1, 2, 4, 8 (column unroll factor)
 * - PREFETCH_A: 1, 2, 4 (prefetch distance)
 *
 * Total: ~2,000 valid configurations (after constraint filtering)
 */

#pragma once

#include <functional>
#include <map>
#include <string>
#include <tuple>
#include <stdexcept>
#include <iostream>

// Forward declarations
namespace llaminar2
{
    class IActivationTensor;
    class Q8_0Tensor;
}

namespace llaminar2
{

    /**
     * @brief Function signature for Q8_1 GEMM kernel
     *
     * @param M Number of rows in A and C
     * @param N Number of columns in B and C
     * @param K Number of columns in A / rows in B
     * @param A Activation tensor (Q8_1 or on-the-fly quantized)
     * @param B Q8_0 weight tensor
     * @param C Output FP32 matrix
     * @param ldc Leading dimension of C
     */
    using Q8_1GemmFunc = std::function<void(
        int M, int N, int K,
        const IActivationTensor &A,
        const Q8_0Tensor &B,
        float *C, int ldc)>;

    /**
     * @brief Registry key: 5-tuple uniquely identifying a Q8_1 GEMM configuration
     *
     * Tuple elements:
     * 0: MR (micro-kernel M dimension)
     * 1: NR (micro-kernel N dimension)
     * 2: JR_BATCH (batched reduction size)
     * 3: JR_UNROLL (column unroll factor)
     * 4: PREFETCH_A (prefetch distance)
     */
    using Q8_1GemmKey = std::tuple<int, int, int, int, int>;

    /**
     * @brief Singleton registry for Q8_1 GEMM kernel instantiations
     *
     * Thread-safe singleton pattern with lazy initialization.
     * Auto-populated by __attribute__((constructor)) functions in generated files.
     */
    class Q8_1GemmKernelRegistry
    {
    public:
        /**
         * @brief Get singleton instance
         * @return Reference to global registry
         */
        static Q8_1GemmKernelRegistry &instance()
        {
            static Q8_1GemmKernelRegistry registry;
            registry.ensureInitialized();
            return registry;
        }

        /**
         * @brief Register a kernel template instantiation
         *
         * Called by __attribute__((constructor)) functions in generated files.
         *
         * @param mr Micro-kernel M dimension
         * @param nr Micro-kernel N dimension
         * @param jr_batch Batched reduction size
         * @param jr_unroll Column unroll factor
         * @param prefetch_a Prefetch distance
         * @param kernel_func Function pointer to template instantiation
         */
        void register_kernel(
            int mr, int nr, int jr_batch, int jr_unroll, int prefetch_a,
            Q8_1GemmFunc kernel_func)
        {
            Q8_1GemmKey key = std::make_tuple(mr, nr, jr_batch, jr_unroll, prefetch_a);

            // Check for duplicate registration
            if (kernels_.count(key) > 0)
            {
                std::cerr << "WARNING: Duplicate Q8_1 GEMM kernel registration: "
                          << "MR=" << mr << ", NR=" << nr
                          << ", JR_BATCH=" << jr_batch
                          << ", JR_UNROLL=" << jr_unroll
                          << ", PREFETCH_A=" << prefetch_a << std::endl;
            }

            kernels_[key] = kernel_func;
        }

        /**
         * @brief Lookup kernel by configuration parameters
         *
         * @param mr Micro-kernel M dimension
         * @param nr Micro-kernel N dimension
         * @param jr_batch Batched reduction size
         * @param jr_unroll Column unroll factor
         * @param prefetch_a Prefetch distance
         * @return Kernel function or nullptr if not found
         */
        Q8_1GemmFunc get_kernel(
            int mr, int nr, int jr_batch, int jr_unroll, int prefetch_a) const
        {
            Q8_1GemmKey key = std::make_tuple(mr, nr, jr_batch, jr_unroll, prefetch_a);

            auto it = kernels_.find(key);
            if (it != kernels_.end())
            {
                return it->second;
            }

            return nullptr; // Not found
        }

        /**
         * @brief Check if kernel exists for given configuration
         *
         * @param mr Micro-kernel M dimension
         * @param nr Micro-kernel N dimension
         * @param jr_batch Batched reduction size
         * @param jr_unroll Column unroll factor
         * @param prefetch_a Prefetch distance
         * @return true if kernel is registered, false otherwise
         */
        bool has_kernel(
            int mr, int nr, int jr_batch, int jr_unroll, int prefetch_a) const
        {
            Q8_1GemmKey key = std::make_tuple(mr, nr, jr_batch, jr_unroll, prefetch_a);
            return kernels_.count(key) > 0;
        }

        /**
         * @brief Get number of registered kernels
         * @return Number of kernels in registry
         */
        size_t size() const
        {
            return kernels_.size();
        }

        /**
         * @brief Get all registered kernel configurations (for debugging/testing)
         * @return Vector of (MR, NR, JR_BATCH, JR_UNROLL, PREFETCH_A) tuples
         */
        std::vector<Q8_1GemmKey> get_all_configs() const
        {
            std::vector<Q8_1GemmKey> configs;
            configs.reserve(kernels_.size());
            for (const auto &kv : kernels_)
            {
                configs.push_back(kv.first);
            }
            return configs;
        }

    private:
        // Private constructor (singleton pattern)
        Q8_1GemmKernelRegistry() = default;

        // Delete copy/move constructors
        Q8_1GemmKernelRegistry(const Q8_1GemmKernelRegistry &) = delete;
        Q8_1GemmKernelRegistry &operator=(const Q8_1GemmKernelRegistry &) = delete;

        void ensureInitialized()
        {
            if (!initialized_)
            {
                extern void forceLink_Q8_1GemmKernelRegistry();
                forceLink_Q8_1GemmKernelRegistry();
                initialized_ = true;
            }
        }

        // Registry storage: map from config key to kernel function
        std::map<Q8_1GemmKey, Q8_1GemmFunc> kernels_;
        bool initialized_ = false;
    };

} // namespace llaminar2
